name: Markdownlint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
    - name: Lint files
      uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
      with:
          config: .markdownlint-cli2.yaml
          globs: '**/*.md'
