name: Markdownlint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22
    - name: Lint files
      uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
      with:
          config: .markdownlint-cli2.yaml
          globs: '**/*.md'
